### ISSUE TITLE
show_band_tool() error

### ISSUE THREAD

**Issue by arafune** [chstan/arpes#15]
Here is the error message of  "example_data.cut.S.show_band_tool()"

ERROR:tornado.application:Uncaught exception GET /autoload.js?bokeh-autoload-element=1001&bokeh-absolute-url=http://localhost:55876&resources=none (::1)
HTTPServerRequest(protocol='http', host='localhost:55876', method='GET', uri='/autoload.js?bokeh-autoload-element=1001&bokeh-absolute-url=http://localhost:55876&resources=none', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/Users/arafune/anaconda/envs/arpes/lib/python3.8/site-packages/tornado/web.py", line 1704, in _execute
    result = await result
  File "/Users/arafune/anaconda/envs/arpes/lib/python3.8/site-packages/bokeh/server/views/autoload_js_handler.py", line 62, in get
    session = await self.get_session()
  File "/Users/arafune/anaconda/envs/arpes/lib/python3.8/site-packages/bokeh/server/views/session_handler.py", line 144, in get_session
    session = await self.application_context.create_session_if_needed(session_id, self.request, token)
  File "/Users/arafune/anaconda/envs/arpes/lib/python3.8/site-packages/bokeh/server/contexts.py", line 243, in create_session_if_needed
    self._application.initialize_document(doc)
  File "/Users/arafune/anaconda/envs/arpes/lib/python3.8/site-packages/bokeh/application/application.py", line 194, in initialize_document
    h.modify_document(doc)
  File "/Users/arafune/anaconda/envs/arpes/lib/python3.8/site-packages/bokeh/application/handlers/function.py", line 143, in modify_document
    self._func(doc)
  File "/Users/arafune/src/arpes/arpes/plotting/band_tool.py", line 330, in tool_handler
    self.center_float_widget.on_change(set_center_float_value)
  File "/Users/arafune/anaconda/envs/arpes/lib/python3.8/site-packages/bokeh/model/model.py", line 434, in on_change
    descriptor = self.lookup(attr)
  File "/Users/arafune/anaconda/envs/arpes/lib/python3.8/site-packages/bokeh/core/has_props.py", line 466, in lookup
    attr = getattr(cls, name, None)
TypeError: getattr(): attribute name must be string
ERROR:tornado.application:Uncaught exception GET /autoload.js?bokeh-autoload-element=1001&bokeh-absolute-url=http://localhost:55876&resources=none (::1)
HTTPServerRequest(protocol='http', host='localhost:55876', method='GET', uri='/autoload.js?bokeh-autoload-element=1001&bokeh-absolute-url=http://localhost:55876&resources=none', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/Users/arafune/anaconda/envs/arpes/lib/python3.8/site-packages/tornado/web.py", line 1704, in _execute
    result = await result
  File "/Users/arafune/anaconda/envs/arpes/lib/python3.8/site-packages/bokeh/server/views/autoload_js_handler.py", line 62, in get
    session = await self.get_session()
  File "/Users/arafune/anaconda/envs/arpes/lib/python3.8/site-packages/bokeh/server/views/session_handler.py", line 144, in get_session
    session = await self.application_context.create_session_if_needed(session_id, self.request, token)
  File "/Users/arafune/anaconda/envs/arpes/lib/python3.8/site-packages/bokeh/server/contexts.py", line 243, in create_session_if_needed
    self._application.initialize_document(doc)
  File "/Users/arafune/anaconda/envs/arpes/lib/python3.8/site-packages/bokeh/application/application.py", line 194, in initialize_document
    h.modify_document(doc)
  File "/Users/arafune/anaconda/envs/arpes/lib/python3.8/site-packages/bokeh/application/handlers/function.py", line 143, in modify_document
    self._func(doc)
  File "/Users/arafune/src/arpes/arpes/plotting/band_tool.py", line 330, in tool_handler
    self.center_float_widget.on_change(set_center_float_value)
  File "/Users/arafune/anaconda/envs/arpes/lib/python3.8/site-packages/bokeh/model/model.py", line 434, in on_change
    descriptor = self.lookup(attr)
  File "/Users/arafune/anaconda/envs/arpes/lib/python3.8/site-packages/bokeh/core/has_props.py", line 466, in lookup
    attr = getattr(cls, name, None)
TypeError: getattr(): attribute name must be string
ERROR:tornado.access:500 GET /autoload.js?bokeh-autoload-element=1001&bokeh-absolute-url=http://localhost:55876&resources=none (::1) 32.24ms
ERROR:tornado.access:500 GET /autoload.js?bokeh-autoload-element=1001&bokeh-absolute-url=http://localhost:55876&resources=none (::1) 32.24ms

**Comment by chstan** [comment]
Hey @arafune,

This looks like an issue with the bokeh and tornado version. Jupyter also uses tornado I believe, and so if Jupyter is installed in the same environment this can create an incompatibility.

I'll look into how to address this long term, but I would advise trying the curve fitting workflow I advocated in the previous thread since it's very efficient (and doesn't depend on what you did in some UI window so it's easily reproducible and visible in the notebook).

Did my comments in that other thread make sense? I should probably add a second tutorial notebook on curve fitting sometime.

Best,
Conrad

**Comment by arafune** [comment]
Hi @chstan,
 
Your comments are arguably useful (you are the author/owner of pyarpes). But a bug is a bug, and I think it should be reported.I think it is important when using open source software for analysis to check whether the software is being actively developed.

It is important from a practical point of view to say, "If you do this, you can avoid the problem". However, if we only use such a solution, we will have to verify the reliability of the analyzed results in a different way.  And I would be less likely to recommend it to my students. 

Ideally: we would have a solution that would
* Solve this problem.
* Turn this function off (temporally). In addition, remove this function from the documentation.
But at least, i think that it is necessary to keep it as a problem.

Best,
